services:
  mssql:
    build: .
    container_name: mssql_server
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=MyStrongPassword123!
    volumes:
      - ./sql:/sql
    networks:
      - mssql_network
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P '$SA_PASSWORD' -Q 'SELECT 1'"]
      interval: 60s
      retries: 5
      start_period: 60s
      timeout: 10s

networks:
  mssql_network:
    driver: bridge